/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clienteWebService.gui;

import java.util.LinkedList;
import javax.swing.JFrame;
import org.clienteWebService.model.Post;

/**
 *
 * @author martin
 */
public class FormClient extends javax.swing.JFrame {

    /**
     * Creates new form FormClient
     */
    public FormClient() {
        initComponents();
    }

    private void showPosts(LinkedList<Post> posts){
        
        PostGUI postPublished;
        panelPosts.removeAll();
        
        for (Post post : posts) {
            postPublished = new PostGUI(post);
            panelPosts.add(postPublished);
            panelPosts.updateUI();
        }
    }

    private void openWindow(JFrame window, JFrame objective){
        window.show();
        window.setSize(window.getPreferredSize());
        window.setLocationRelativeTo(objective);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBlog = new javax.swing.JFrame();
        panelNewPost = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPostTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPostContent = new javax.swing.JTextArea();
        btnAddPost = new javax.swing.JButton();
        panelPosts = new javax.swing.JPanel();
        formAdmin = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnWritePostA = new javax.swing.JButton();
        btnListPostsA = new javax.swing.JButton();
        formWritePost = new javax.swing.JFrame();
        panelNewPost2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPostTitleA = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPostContentA = new javax.swing.JTextArea();
        btnAddPostA = new javax.swing.JButton();
        formBlog1 = new javax.swing.JFrame();
        panelNewPost1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPostTitle1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPostContent1 = new javax.swing.JTextArea();
        btnAddPost1 = new javax.swing.JButton();
        panelPosts1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        panelNewPost.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Post"));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel4.setText("Título: ");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setText("Texto: ");

        txtPostContent.setColumns(20);
        txtPostContent.setRows(5);
        jScrollPane1.setViewportView(txtPostContent);

        btnAddPost.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddPost.setText("Añadir post");
        btnAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewPostLayout = new javax.swing.GroupLayout(panelNewPost);
        panelNewPost.setLayout(panelNewPostLayout);
        panelNewPostLayout.setHorizontalGroup(
            panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPostLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtPostTitle))
            .addGroup(panelNewPostLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
        );
        panelNewPostLayout.setVerticalGroup(
            panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewPostLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPost)
                .addContainerGap())
        );

        panelPosts.setBorder(javax.swing.BorderFactory.createTitledBorder("Posts"));
        panelPosts.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout formBlogLayout = new javax.swing.GroupLayout(formBlog.getContentPane());
        formBlog.getContentPane().setLayout(formBlogLayout);
        formBlogLayout.setHorizontalGroup(
            formBlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBlogLayout.createSequentialGroup()
                .addGroup(formBlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBlogLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelPosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelNewPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formBlogLayout.setVerticalGroup(
            formBlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNewPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Menú de Operaciones");

        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        btnWritePostA.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnWritePostA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/clienteWebService/resources/writePost.png"))); // NOI18N
        btnWritePostA.setText("Redactar Post");
        btnWritePostA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWritePostA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWritePostA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWritePostAActionPerformed(evt);
            }
        });
        jPanel2.add(btnWritePostA);

        btnListPostsA.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnListPostsA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/clienteWebService/resources/listPosts.png"))); // NOI18N
        btnListPostsA.setText("Listar Posts");
        btnListPostsA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListPostsA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListPostsA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPostsAActionPerformed(evt);
            }
        });
        jPanel2.add(btnListPostsA);

        javax.swing.GroupLayout formAdminLayout = new javax.swing.GroupLayout(formAdmin.getContentPane());
        formAdmin.getContentPane().setLayout(formAdminLayout);
        formAdminLayout.setHorizontalGroup(
            formAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(formAdminLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        formAdminLayout.setVerticalGroup(
            formAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelNewPost2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Post"));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Título: ");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel10.setText("Texto: ");

        txtPostContentA.setColumns(20);
        txtPostContentA.setRows(5);
        jScrollPane3.setViewportView(txtPostContentA);

        btnAddPostA.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddPostA.setText("Finalizar Redacción");
        btnAddPostA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewPost2Layout = new javax.swing.GroupLayout(panelNewPost2);
        panelNewPost2.setLayout(panelNewPost2Layout);
        panelNewPost2Layout.setHorizontalGroup(
            panelNewPost2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPost2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtPostTitleA))
            .addGroup(panelNewPost2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(panelNewPost2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPostA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
        );
        panelNewPost2Layout.setVerticalGroup(
            panelNewPost2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPost2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewPost2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPostTitleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewPost2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewPost2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPostA)
                .addContainerGap())
        );

        javax.swing.GroupLayout formWritePostLayout = new javax.swing.GroupLayout(formWritePost.getContentPane());
        formWritePost.getContentPane().setLayout(formWritePostLayout);
        formWritePostLayout.setHorizontalGroup(
            formWritePostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(formWritePostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formWritePostLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelNewPost2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        formWritePostLayout.setVerticalGroup(
            formWritePostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(formWritePostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formWritePostLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelNewPost2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        panelNewPost1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Post"));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel6.setText("Título: ");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel7.setText("Texto: ");

        txtPostContent1.setColumns(20);
        txtPostContent1.setRows(5);
        jScrollPane2.setViewportView(txtPostContent1);

        btnAddPost1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddPost1.setText("Añadir post");
        btnAddPost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPost1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewPost1Layout = new javax.swing.GroupLayout(panelNewPost1);
        panelNewPost1.setLayout(panelNewPost1Layout);
        panelNewPost1Layout.setHorizontalGroup(
            panelNewPost1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPost1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtPostTitle1))
            .addGroup(panelNewPost1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(panelNewPost1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPost1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)))
        );
        panelNewPost1Layout.setVerticalGroup(
            panelNewPost1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPost1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewPost1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPostTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewPost1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewPost1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPost1)
                .addContainerGap())
        );

        panelPosts1.setBorder(javax.swing.BorderFactory.createTitledBorder("Posts"));
        panelPosts1.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout formBlog1Layout = new javax.swing.GroupLayout(formBlog1.getContentPane());
        formBlog1.getContentPane().setLayout(formBlog1Layout);
        formBlog1Layout.setHorizontalGroup(
            formBlog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBlog1Layout.createSequentialGroup()
                .addGroup(formBlog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBlog1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelPosts1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelNewPost1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formBlog1Layout.setVerticalGroup(
            formBlog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBlog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNewPost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPosts1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setText("Nick: ");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña: ");

        txtPassword.setText("jPasswordField1");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/clienteWebService/resources/login.png"))); // NOI18N

        btnLogin.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnLogin.setText("Ingresar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNick)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPostActionPerformed

        
    }//GEN-LAST:event_btnAddPostActionPerformed

    private void btnAddPost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPost1ActionPerformed

    private void btnAddPostAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPostAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPostAActionPerformed

    private void btnWritePostAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWritePostAActionPerformed

        openWindow(formWritePost, formAdmin);
    }//GEN-LAST:event_btnWritePostAActionPerformed

    private void btnListPostsAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPostsAActionPerformed

    }//GEN-LAST:event_btnListPostsAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormClient().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPost;
    private javax.swing.JButton btnAddPost1;
    private javax.swing.JButton btnAddPostA;
    private javax.swing.JButton btnListPostsA;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnWritePostA;
    private javax.swing.JFrame formAdmin;
    private javax.swing.JFrame formBlog;
    private javax.swing.JFrame formBlog1;
    private javax.swing.JFrame formWritePost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelNewPost;
    private javax.swing.JPanel panelNewPost1;
    private javax.swing.JPanel panelNewPost2;
    private javax.swing.JPanel panelPosts;
    private javax.swing.JPanel panelPosts1;
    private javax.swing.JTextField txtNick;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextArea txtPostContent;
    private javax.swing.JTextArea txtPostContent1;
    private javax.swing.JTextArea txtPostContentA;
    private javax.swing.JTextField txtPostTitle;
    private javax.swing.JTextField txtPostTitle1;
    private javax.swing.JTextField txtPostTitleA;
    // End of variables declaration//GEN-END:variables
}
