/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.clienteWebService.gui;

import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.clienteWebService.model.Post;
import org.clienteWebService.model.Usuario;
import org.clienteWebService.net.Linker;
import org.jespxml.JespXML;
import org.jespxml.excepciones.TagHijoNotFoundException;
import org.jespxml.modelo.Tag;
import org.xml.sax.SAXException;

/**
 *
 * @author martin
 */
public class FormClient extends javax.swing.JFrame {

    Usuario localUser;
    
    public FormClient() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void showPosts(LinkedList<Post> posts){
        
        PostGUI postPublished;
        panelPosts.removeAll();
        
        for (Post post : posts) {
            postPublished = new PostGUI(post);
            panelPosts.add(postPublished);
            panelPosts.updateUI();
        }
    }

    private void openWindow(JFrame window, JFrame objective){
        window.show();
        window.setSize(window.getPreferredSize());
        window.setLocationRelativeTo(objective);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formBlog = new javax.swing.JFrame();
        panelNewPost = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPostTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPostContent = new javax.swing.JTextArea();
        btnAddPost = new javax.swing.JButton();
        panelPosts = new javax.swing.JPanel();
        formAdmin = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnWritePostA = new javax.swing.JButton();
        btnListPostsA = new javax.swing.JButton();
        formWritePost = new javax.swing.JFrame();
        panelNewPost2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPostTitleA = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPostContentA = new javax.swing.JTextArea();
        btnAddPostA = new javax.swing.JButton();
        formBlog1 = new javax.swing.JFrame();
        panelNewPost1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPostTitle1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPostContent1 = new javax.swing.JTextArea();
        btnAddPost1 = new javax.swing.JButton();
        panelPosts1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNick = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        panelNewPost.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Post"));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel4.setText("Título: ");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel5.setText("Texto: ");

        txtPostContent.setColumns(20);
        txtPostContent.setRows(5);
        jScrollPane1.setViewportView(txtPostContent);

        btnAddPost.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddPost.setText("Añadir post");
        btnAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewPostLayout = new javax.swing.GroupLayout(panelNewPost);
        panelNewPost.setLayout(panelNewPostLayout);
        panelNewPostLayout.setHorizontalGroup(
            panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPostLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtPostTitle))
            .addGroup(panelNewPostLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)))
        );
        panelNewPostLayout.setVerticalGroup(
            panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewPostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPostTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNewPostLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPost)
                .addContainerGap())
        );

        panelPosts.setBorder(javax.swing.BorderFactory.createTitledBorder("Posts"));
        panelPosts.setLayout(new java.awt.GridLayout(0, 1));

        javax.swing.GroupLayout formBlogLayout = new javax.swing.GroupLayout(formBlog.getContentPane());
        formBlog.getContentPane().setLayout(formBlogLayout);
        formBlogLayout.setHorizontalGroup(
            formBlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBlogLayout.createSequentialGroup()
                .addGroup(formBlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBlogLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelPosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelNewPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formBlogLayout.setVerticalGroup(
            formBlogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBlogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNewPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPosts, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Menú de Operaciones");

        jPanel2.setLayout(new java.awt.GridLayout(0, 2));

        btnWritePostA.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnWritePostA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/clienteWebService/resources/writePost.png"))); // NOI18N
        btnWritePostA.setText("Redactar Post");
        btnWritePostA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWritePostA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWritePostA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWritePostAActionPerformed(evt);
            }
        });
        jPanel2.add(btnWritePostA);

        btnListPostsA.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btnListPostsA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/clienteWebService/resources/listPosts.png"))); // NOI18N
        btnListPostsA.setText("Listar Posts");
        btnListPostsA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListPostsA.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListPostsA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPostsAActionPerformed(evt);
            }
        });
        jPanel2.add(btnListPostsA);

        javax.swing.GroupLayout formAdminLayout = new javax.swing.GroupLayout(formAdmin.getContentPane());
        formAdmin.getContentPane().setLayout(formAdminLayout);
        formAdminLayout.setHorizontalGroup(
            formAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(formAdminLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        formAdminLayout.setVerticalGroup(
            formAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelNewPost2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Post"));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Título: ");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel10.setText("Texto: ");

        txtPostContentA.setColumns(20);
        txtPostContentA.setRows(5);
        jScrollPane3.setViewportView(txtPostContentA);

        btnAddPostA.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnAddPostA.setText("Finalizar Redacción");
        btnAddPostA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNewPost2Layout = new javax.swing.GroupLayout